fix: pin unwinding version to 0.2.8
Version 0.2.9 of unwinding breaks the build with:

```
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.9/src/panicking.rs:42:19
   |
42 |         return if core::intrinsics::catch_unwind(do_call::<F, R>, data_ptr, do_catch::<E>) {
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `i32`
```

We pin it to 0.2.8 until we do the big merge and can address this issue.